### ISSUE TITLE
Include Date and Time in Embed

### ISSUE THREAD

**Issue by joshuacant** [FixTweet/FixTweet#120]
Currently the embed does not include the date or time of the tweet. Quite a lot of context to a tweet is lost without knowing when it was posted. Is it possible to include that in the embed?

**Comment by dangeredwolf** [comment]
AFAIK, Discord and Telegram (the platforms we target most) don't support rendering UI for any opengraph tags related to date/time. It would be possible to shoot it into the tweet content or website title, but it either eats into the already-limited content length for the Tweet, or makes embeds less elegant since it must include the full date and/or time to really match what Twitter displays.

It's a good idea, just not sure how to implement it in a way that makes the most sense given the limitations we're working with.

It might work okay in Discord if we replace the OEmbed provider text that normally just says FixTweet or something similar. Maybe.

**Comment by dangeredwolf** [comment]
FixTweet embeds are cached on the edge so using relative times (like hours ago) is a bad idea. It's also a bad idea because embeds also don't get updated after they are created. Absolute dates could be made to work, if we can do it in a way that works well.

**Comment by onchodila** [comment]
Maybe you already know this but Discord has a way to post time/date via Unix timestamps: https://discord.com/developers/docs/reference#message-formatting-timestamp-styles It shows the time in the viewers timezone and formatting and language. There's a relative time variation that works in embeds. Should work for this?

This works in any embed, you can tweet the codes and they work if someone links the tweet in discord.

This website uses this to make sharing dates and time across discord very handy https://hammertime.cyou

**Comment by dangeredwolf** [comment]
@onchodila Issue there is that normal website embeds don't get to use Discord's special formatting

**Comment by onchodila** [comment]
Huh, really? I didn't know that twitter embeds were special but looks like you're right..

I had heard stories about twitch vod titles accidentally getting spoiler tags though.. maybe that's changed.

**Comment by dangeredwolf** [comment]
Telegram lets us display date with Instant View (and it localizes date!), but Discord still doesn't have a parameter to let us do the same. Given the issues I laid out with doing this on Discord (no space that makes sense imo, no localization, no relative times) I don't think it makes sense to implement at the moment. But if Discord improves their embeds it might be possible to render dates and other formatting in the future (if Discord let us use their formatting in their embeds this would be easy as they have timestamp syntax!)
