### ISSUE TITLE
Feature request: Fetch user profiles 

### ISSUE THREAD

**Issue by Wazbat** [FixTweet/FixTweet#185]
I was looking through the source code and noticed the ability to request data as tweets JSON which is super useful!

I was looking though and it appears the user endpoints only redirect back to the main profile. It'd be pretty useful to be able to fetch user profiles via this endpoint. This could also resolve #110

I might be down to try implementing this myself if you'd like that, as the whole project is well structured and it looks easy enough to do. I think it'd be a good way to lay the ground work for a special user embedd, as I noticed in a comment this was something that could be done in the future

**Comment by dangeredwolf** [comment]
This is def something I have wanted to implement, I just haven't gotten around to it. If you want to try to implement it I'd be down, otherwise I probably will do it at some point anyway.

**Comment by Wazbat** [comment]
I was exploring the webapp a little and I think I found the request that does it, however I'm having a bit of trouble figuring out how to actually run and debug the code locally. How do you test it on your machine?

**Comment by dangeredwolf** [comment]
I actually test live using a separate subdomain on Cloudflare, however it runs under Miniflare as well for local testing, which is actually what the unit tests do.

Given FixTweet is primarily about getting embeds, I personally always test it out in the open on a different subdomain because that's the only way embeds are gonna work :P

You could also get it working with [workerd](https://github.com/cloudflare/workerd), which became open-source a few months ago.

**Comment by AoSankaku** [comment]
Hello,

I created a script that lets Carl-bot edit the url of `x.com` or `twitter.com` into `fxtwitter.com`, and it is basically working fine, except for profile URLs.
So would you reopen and work on this issue again?

**Comment by AoSankaku** [comment]
Here is a screenshot, expected embed view is not shown.

![image](https://github.com/FixTweet/FixTweet/assets/58819229/c92c7e56-b051-4e36-b075-8737cb81f80b)
