### ISSUE TITLE
Change readme.md to include iMessage

### ISSUE THREAD

**Issue by SpyderThingy** [FixTweet/FixTweet#359]
you just unintentionally fixed embeds for imessage, congratulations

**Comment by dangeredwolf** [comment]
Our 2 primary platform targets we routinely test our embeds for are Discord and Telegram as they are by far the most popular clients used by our users. We do not officially target other platforms, however, many of them including iMessage, Slack, etc. implement OpenGraph and other standards to be able to read our embeds just fine--we'll give them to any user agent that appears to be an automated crawler. But since we don't test for iMessage, I don't think it's worth including in the README. However, I did update the wording to say "and more" as it does indeed work with some other platforms.

**Comment by SpyderThingy** [comment]
thx man, appreciate you making this for us
