### ISSUE TITLE
Discord spoilers embed the GitHub, not the Tweet

### ISSUE THREAD

**Issue by Seltyk** [FixTweet/FixTweet#482]
A Discord message containing a spoiler'd link should embed and spoiler the link target. However, fixupx.com and fxtwitter.com instead embed the FixTweet project GitHub rather than the intended Tweet. The link, of course, works as expected, as does Discord's spoiler blur.

Curiously, vxtwitter.com embeds the Tweet as one would expect.

Example:
![image](https://github.com/FixTweet/FixTweet/assets/6631431/dd30f6df-8159-4644-b294-4784ae2773eb)

**Comment by dangeredwolf** [comment]
That is odd. I quickly pin-pointed that this is because Discord is actually sending us the URL with `||` after it because of the spoiler, so if you put `https://fxtwitter.com/jack/status/20` in spoilers, what we actually receive is `https://fxtwitter.com/jack/status/20||`. If this ever worked before, it was before with our old routing implementation which had a bit of a looser configuration, but it seems we'll have to fix this to make it work. Why Discord is parsing the spoiler syntax in the URL is beyond me.

**Comment by dangeredwolf** [comment]
The fix should be live now, but you'll have to regenerate your currently broken embeds. You can simply change the username to `i` or add a query string (`?asdf`) at the end to regenerate the embed.

**Comment by Seltyk** [comment]
Confirmed fixed.
