### ISSUE TITLE
Image and video embeds look different

### ISSUE THREAD

**Issue by angus-lherrou** [FixTweet/FixTweet#501]
When embedding a tweet with a video versus an image, there is no engagement text and the text of the tweet appears above the author's display name and username instead of below.

Example:

<img width="445" alt="Screenshot 2023-11-20 at 11 18 19 AM" src="https://github.com/FixTweet/FixTweet/assets/55718851/1de38cc8-b839-4af2-b33c-5c5cf9a3f6e3">
<img width="456" alt="Screenshot 2023-11-20 at 11 18 10 AM" src="https://github.com/FixTweet/FixTweet/assets/55718851/a4a523dd-1714-467b-9359-810d52cb179c">

**Comment by angus-lherrou** [comment]
A note: this is especially noticeable on Discord for iOS, where the text of the video embed is gray instead of white, and thus very easy to overlook.

**Comment by dangeredwolf** [comment]
This is a limitation of the way Discord embeds videos. The part that normally displays the text of a tweet is not available for website embeds that have video. Bot embeds don't have the same limitations that we do, and that's why we format videos the way that we do. Though it's funny that I'm learning about Snoop Dogg giving up smoking from a GitHub issue.
