### ISSUE TITLE
Is there any way to not combine images together into a single image?

### ISSUE THREAD

**Issue by Hexerin** [FixTweet/FixTweet#512]
I regularly transfer tweets over to my personal Discord to share the goings-on about game events and whatnot, and these tweets generally have multiple images attached. For example, [this](https://twitter.com/ArknightsEN/status/1727884753045729528).

However, when this service provides its embed, all images in the tweet are merged into a single image. Example:

![18b8a2f1dc4e41ae1cab5d6573c615f6](https://github.com/FixTweet/FixTweet/assets/42397404/a3827af2-9fac-49a9-9e52-de60fcd9a006)

VXTwitter does the same thing, although their method is _significantly_ worse about it. They put the images together in an unreadable square, whereas FXTwitter appears to put them in a convenient scrolling vertical.

I'm aware of the method you have to embed specific images, that doesn't help me because I need all the images available. I need the embed to include all the images, but have each image be individually viewable. Is this currently doable? If not, can this be added as a feature? If neither, does anyone know of a similar service to FXTwitter and VXTwitter, that does this?

**Comment by dangeredwolf** [comment]
We mention this in the Q&A of the repo:

https://github.com/FixTweet/FixTweet#what-if-i-dont-want-fixtweet-to-combine-my-posts-images-together-with-multi-image

You can just add `/photo/1` for 1st photo, etc. Same syntax as Twitter.

`https://fxtwitter.com/example/status/123/photo/1`

**Comment by dangeredwolf** [comment]
Unfortunately, website embeds on Discord cannot have multiple images, which is exactly why we combine them by default. We can't do anything about that on our end. Discord bots and webhooks can, however, embed multiple images. The now-broken Discord official Twitter embeds used bot/webhook embeds which is why they look different from fxtwitter and every other website with embeds, and why multiple images could be individually clicked on there.
