### ISSUE TITLE
Dynamic embed colour broke

### ISSUE THREAD

**Issue by red-star-fighter** [FixTweet/FixTweet#514]
I've recently started to use FX Twitter again and it seems that dynamic embed colours no longer work. Previously, the embed colour would be chosen based on the predominant colour in a piece of media, and otherwise stay blue. Now, the colour is always blue, even when a picture is in the embed.

**Comment by dangeredwolf** [comment]
This happened because we switched from API v2 to GraphQL because they removed the endpoints we were relying on. The GraphQL versions of these endpoints don't include the color data we were pulling from, so this feature has been disabled ever since. If we can find a way to get this data again I'd love to re-add it, but I don't see any way to do it at the moment.
