### ISSUE TITLE
Weird issue if twitter link doesn't end with a /

### ISSUE THREAD

**Issue by OshidaBCF** [FixTweet/FixTweet#554]
I just got the bug, and for some reason if the link doesn't end with a / it show a random picture with some random text, maybe some debug thing ?

but the tag is the actual one

![image](https://github.com/FixTweet/FixTweet/assets/61458287/2a1886b9-b0f2-49ed-a8a9-865cbd18a8d0)

**Comment by dangeredwolf** [comment]
![image](https://github.com/FixTweet/FixTweet/assets/2636265/29e0fdf2-df91-41a9-bfc2-42578f25a69c)
Sorry to hear you're having issues. I guess the good(?) news is that it seems to work again now, but I have no idea how in the world it showed you a different tweet, it should obviously never do that.

**Comment by dangeredwolf** [comment]
Because per our own privacy policy, we don't log individual requests, so I have no idea why it's showing some stupid crypto account (id 1735029002719404097) instead of the content you asked for (id 1734948316553904560). These tweets have no relation to each other (i checked to be sure it wasn't a reply to the intended tweet or anything because if we somehow had a parsing bug on our end then it will probably be related). 

![image](https://github.com/FixTweet/FixTweet/assets/2636265/acb4ca5f-0716-492b-8ee1-10325a9ea894)

You can pull data directly from our API and no matter how many times you request it, it returns the correct tweet (occasionally updating stuff like likes and retweets since our API returns uncached data, unlike embeds).

Since we cache embeds and so does Discord normally it's possible there could have been cache poisoning, but if there was, I can't reproduce it again (and if it's on discord's end, that's pretty fucking bad)

The reason the embed worked the second time is because by adding the slash, you are changing the cache url and it is therefore treated as different (same if you add a query string, like `https://fxtwitter.com/i/status/20?asd`)

**Comment by dangeredwolf** [comment]
I've seen embed poisoning on Telegram plenty of times but not on Discord because of the differences in how both platforms generate them, so I have no idea where to even begin to figure out what went wrong tbh

**Comment by OshidaBCF** [comment]
yup it's working fine again

i'm just gonna blame it on twitter

thks for checking tho
