### ISSUE TITLE
Longer text cutting off with embeds

### ISSUE THREAD

**Issue by cobrabr** [FixTweet/FixTweet#74]
Example: https://twitter.com/NoLieWithBTC/status/1569451415843774466

![image](https://user-images.githubusercontent.com/724969/190009447-221aa75d-6ddb-4a5e-987f-59b298f645f0.png)

![image](https://user-images.githubusercontent.com/724969/190009320-bcfb0eb0-184e-46d0-98cc-bc4b52e032d6.png)

**Comment by dangeredwolf** [comment]
We limit the amount of text that can be displayed in our embeds because our embeds work differently from Discord's (because Discord Twitter embeds tap into bot rich embeds while we can't). I'm not 100% on the hard limit, but we cap it at 200 because some Tweets above that have broken. There are definitely improvements to be made, like using ellipsis instead of just cutting off the text, etc

**Comment by dangeredwolf** [comment]
I forgot to update this issue as I've introduced as good of a fix as I could
* It will now show up to Discord's maximum of 256 characters in the author text field (even 257 characters will break embed)
* If it exceeds 256 characters, it is truncated with an ellipsis so you know there is more to it

Actually, these fixes were introduced a while ago, but I only increased it from 250 to 256 characters now (I forgot to run experiments to see the proper maximum until now)
