### ISSUE TITLE
Support individual multimedia links in multimedia posts

### ISSUE THREAD

**Issue by LeviSnoot** [FixTweet/FixTweet#96]
Similar to #95, but in the case where I want to append for example `/video/2` (and even `https://d.twittpr.com/.../video/2.mp4`) to a URL in order to only embed the video in the post it does not appear to work.

**Comment by dangeredwolf** [comment]
yeah, because of the way FixTweet structures and separates media data it makes it a bit quirky now that Twitter is mixing media types. So we'll probably need to rework some things internally to improve this.

**Comment by dangeredwolf** [comment]
I went to tackle this issue again, rewrote a bunch of FixTweet's media handling code in an effort to streamline it and make this easier to fix.... buuuut it turns out I underestimated the issue. Twitter isn't even sending us multiple videos. I might have to migrate the entire API fetch system to graphql, not looking forward to doing that 💀

**Comment by dangeredwolf** [comment]
This appears to have been resolved at some point after we moved to GraphQL API. `media.all` in our API returns photos, videos, and gifs in the order they appear on Twitter, and direct media redirects also appear to work. Closing for now, but if you are still encountering this issue, please give an example URL and I can take a look!
